[paths]
training='/n/groups/datta/win/longtogeny/data/size_network/training_data/3month-male-multi_animal_training_data.h5'
validation='/n/groups/datta/win/longtogeny/data/size_network/male_ontogeny_validation.h5'
age_validation='/n/groups/datta/win/longtogeny/data/size_network/male_ontogeny_pose_balanced_validation.h5'

wall_noise='/n/groups/datta/win/longtogeny/data/size_network/training_data/wall_noise.h5'
saving='/n/groups/datta/win/longtogeny/size_norm/models/pre_final_model-2023-08-02'
# saving='/n/groups/datta/win/longtogeny/size_norm/models/continuous-gradient-size-test-with-l2-2023-07-29'

[augmentation]
angle_range = [-60, 60]
scale_x = [0.45, 1.7]
scale_y = [0.45, 1.7]
scale_z = [0.7, 1.3]
translate_x = [-0.2, 0.2]  # proportional
translate_y = [-0.3, 0.3]  # proportional
height = [-7, 7]
white_noise_scale = 3

elastic_alpha = 1.75
elastic_sigma = 9.0
elastic_ksize = 61
elastic_flag = true

rotation_prob = 0.7
translation_prob = 0.7
scale_prob = 0.7
height_offset_prob = 0.7
height_scale_prob = 0.7
preserve_aspect_prob = 0.6
white_noise_prob = 0.3
flip_prob = 0.5
elastic_warp_prob = 0.2
random_elastic_prob = 0.2
tps_warp_prob = 0.2
wall_reflection_prob = 0.1

seed = 4

[callbacks.dynamics_validation]
log_interval = 500  # epochs
max_frames = 6000

[callbacks.age_validation]
log_interval = 500  # epochs
max_frames = 6000

[callbacks.stopping]
patience = 35  # epochs

[trainer]
max_epochs = 501

[model]
depth = 4
init_channel = 256
input_channel = 32
init_depth = 1
channel_scaling = 2
depth_scaling = 1.0
activation = 'GELU'

[model.lightning]
adversarial_prob = 0.01
lr = 0.001
weight_decay = 0.00001
arch = 'ae'  # ae, unet, efficient, efficient_unet
train_adversarial = false
adversarial_age_lr = 1e-4
jit = true
adversarial_arch = "nonlinear"  # linear, nonlinear
adversarial_type = "continuous"  # class, continuous
adversarial_init_epoch = 25
max_grad = 100  # gradient clipping
use_l2_regularization_class = false
l2_regularization_class_alpha = 5e-4
use_l2_regularization_sn = false
l2_regularization_sn_alpha = 5e-4

[model.lightning.lr_scheduler_params]
patience = 25

# scaling magnitude of age-based adversarial loss
[model.lightning.adversarial_age_scaling]
start_epoch = 30
start_value = 1e-7
max_value = 2e-4
epochs_to_max = 30

[model.ae]
double_conv = true
separable = true
residual = true

[model.unet]
double_conv = true
separable = true
residual = false

[model.efficient]
fused = 1
expansion = 4

[model.efficient_unet]
fused = 1
expansion = 4