[paths]
saving = '/n/groups/datta/win/longtogeny/size_norm/models/big_param_scan_00'

# stage 1: find model architecture that maximizes performance - vary number of parameters
[stage1.model]
arch = ['ae', 'unet', 'efficient', 'efficient_unet']
init_channel = [4, 8, 16, 32, 64, 128, 256, 512]  # list
channel_scaling = { start = 1.5, stop = 4.0, num = 6 }

# stage 2 - fix arch, network depth
[stage2.model]
depth = { start = 2, stop = 5, step = 1 }

# stage 3 - fix arch, other model params
[stage3.model]
activation = ['ReLU', 'ELU', 'LeakyReLU', 'SiLU', 'GELU']  # list

# stage 4 - fix arch, other model params
[stage4.model]
double_conv = [true, false]
residual = [true, false]

# stage 5 - fixed model parameters, training hyperparameters
[stage5.model]
adversarial_prob = { start = 0.0, stop = 1.0, num = 6 }
lr = { start = -4, stop = -2, num = 3, type = 'log' }
weight_decay = { start = -6, stop = -3, num = 4, type = 'log' }

# stage 6 - fixed model parameters, adversarial age model parameters
[stage6.model]
adversarial_arch = ["linear", "nonlinear"]
adversarial_type = ["class", "continuous"]
