[paths]
saving = '/n/groups/datta/win/longtogeny/size_norm/models/param_scan'

# first, scan over model parameters, instead of augmentation parameters
# use best model to scan over augmentation parameters
# [augmentation]
# scale_x = [0.1, 2.5]
# scale_y = [0.1, 2.5]


[model]
channels = [2, 4, 8, 16, 24, 32, 64, 128, 256, 512, 1024]
channel_depth = [1, 5]
separable = [false, true]
adversarial_prob = [0, 1]
lr = [-4, -2]
weight_decay = [-6, -3]
arch = ['ae', 'unet']