[paths]
saving = '/n/groups/datta/win/longtogeny/size_norm/models/param_scan_06'

[model.stage1]  # model depth and width
depth = [2, 4]  # range
arch = ['ae', 'unet', 'efficient', 'efficient_unet']
init_channel = [4, 8, 16, 32, 64, 128]  # list

[model.stage2]
arch = ['ae', 'unet', 'efficient', 'efficient_unet']
init_channel = [4, 8, 16, 32]  # list
channel_scaling = [2.5, 4.0, 4.0]


[model.stage3]  # model hyperparameters
activation = ['ReLU', 'ELU', 'LeakyReLU', 'SiLU', 'GELU']  # list
adversarial_prob = [0.0, 1.0, 6.0]
lr = [-4, -2, 3]
weight_decay = [-6, -3, 4]
