[paths]
saving = '/n/groups/datta/win/longtogeny/size_norm/models/vae_param_scan_00'

# stage 1: bottleneck
[stage1.model]
arch = ['vae']
bottleneck = [1, 3, 5, 7, 9, 10, 25, 50, 100, 250, 500, 1000]
double_conv = [false]
init_channel = [64]