[paths]
training='/n/groups/datta/win/longtogeny/data/size_network/training_data/3month-male-multi_animal_training_data.h5'
validation='/n/groups/datta/win/longtogeny/data/size_network/male_ontogeny_validation.h5'
# training='/n/groups/datta/win/longtogeny/data/size_network/training_data/multi_animal_training_data.h5'
# validation='/n/groups/datta/win/longtogeny/data/size_network/female_ontogeny_validation.h5'

wall_noise='/n/groups/datta/win/longtogeny/data/size_network/training_data/wall_noise.h5'
saving='/n/groups/datta/win/longtogeny/size_norm/models/param_scan_02'

[augmentation]
angle_range = [-80, 80]
scale_x = [0.4, 1.7]
scale_y = [0.4, 1.7]
translate_x = [-0.2, 0.2]  # proportional
translate_y = [-0.3, 0.3]  # proportional
height = [-5, 5]
white_noise_scale = 3

elastic_alpha = 2.0
elastic_sigma = 9.0
elastic_ksize = 61

affine_prob = 0.7
preserve_aspect_prob = 0.5
white_noise_prob = 0.3
flip_prob = 0.5
elastic_warp_prob = 0.2
random_elastic_prob = 0.2
tps_warp_prob = 0.2
wall_reflection_prob = 0.1

seed = 0

[model]
depth = 4
init_channel = 8
input_channel = 16
init_depth = 1
channel_scaling = 2.0
depth_scaling = 1.0
activation = 'LeakyReLU'

[model.lightning]
adversarial_prob = 0.2
lr = 0.001
weight_decay = 0.00001
arch = 'ae'  # ae, unet, efficient

[model.ae]
double_conv = true
separable = true

[model.unet]
double_conv = true
separable = true

[model.efficient]
fused = 2
expansion = 4