[paths]
saving = '/n/groups/datta/win/longtogeny/size_norm/models/bottleneck_optimization_00'

[stage1.model]
arch = ['ae', 'vae']
init_channel = [16, 32, 64, 128, 256, 512]
double_conv = [false]
bottleneck = [5, 9, 25, 50]
